'\" t
.\"     Title: khal
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/07/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "KHAL" "1" "05/07/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
khal \- a command line calendar
.SH "SYNOPSIS"
.sp
\fBkhal\fR calendar [\-vc CONF] [ (\-a CAL \&... | \-d CAL \&... ) ] [DATE]
.sp
\fBkhal\fR agenda [\-vc CONF] [ (\-a CAL \&... | \-d CAL \&... ) ] [DATE]
.sp
\fBkhal\fR interactive [\-vc CONF] [ (\-a CAL \&... | \-d CAL \&... ) ]
.sp
\fBkhal\fR new [\-vc CONF] [\-a cal] DESCRIPTION\&...
.sp
\fBkhal\fR [\-vc CONF] printcalendars
.sp
\fBkhal\fR (\-h | \-\-help)
.sp
\fBkhal\fR \-\-version
.sp
\fBkhal\fR
.sp
\fBikhal\fR
.SH "DESCRIPTION"
.sp
khal(1) is a standards based command line calendar program\&. It uses \fIvdir\fR for calendar storage\&. \fIvdir\fR can be synced with CalDAV servers via vdirsyncer(1)\&. khal allows editing, deleting and adding of events to your calendars\&.
.SH "OPTIONS"
.PP
\fB\-c\fR=\fICONFIG\fR
.RS 4
Use the configuration file
\fICONFIG\fR, otherwise
\fBkhal(1)\fR
will look in
\fI$HOME/\&.khal/\fR
and
\fI$HOME/\&.config/khal/\fR
for files named
\fIkhal\&.conf\fR\&.
.RE
.PP
\fB\-v\fR
.RS 4
Be extra verbose\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print khal\(cqs version number and exit\&.
.RE
.PP
\fB\-a\fR=\fINAME\fR
.RS 4
Use the calendar
\fINAME\fR
(this option can be used more than once with most commands)\&.
.RE
.PP
\fB\-d\fR=\fINAME\fR
.RS 4
Do not use the calendar
\fINAME\fR
(this option can be used more than once with most commands)\&.
.RE
.SH "COMMANDS"
.sp
Khal is divided into several commands which are called as \fBkhal COMMAND\fR\&. See below for a description of the seperate commands\&. If you call \fBkhal\fR without any commands the default command will be executed (can be configured in the configuration file)\&.
.SS "agenda"
.sp
Show all events scheduled for today and tommorow\&.
.SS "calendar"
.sp
Show a calendar of the current and next two months and all events scheduled for today and tomorrow\&.
.SS "interactive"
.sp
Opens khal\(cqs interactive mode\&. Use the arrow keys to navigate in the calendar\&. Press \fITab\fR or \fIEnter\fR to move the focus into the events column and Left arrow to return the focus to the calendar area\&. You can navi\(hy gate the events column with the Up and Down arrows and view an event via pressing Enter d will delete an event (a D will appear in front of the events description, or RO if you cannot delete that event)\&. Pressing d again will undelete that event\&.
.sp
When viewing an event\(cqs details, pressing Enter again will open the currently selected event in a simple event editor; you can navigate with the arrow keys again\&. As long as the event has not been edited you can leave the editor with pressing Escape Cancel button and press the Enter key to discard your edits or press the Save button to save your edits (and upload them on the next sync)\&.
.sp
While the calendar area is focused, pressing n will add a new event on the currently selected date\&.
.sp
\fBikhal\fR is a shortcut for \fIkhal interactive\fR\&.
.SS "new"
.sp
Add a new event\&. \fInew\fR supports the following syntax: \fIkhal new [\-a CALENDAR] startdatetime [enddatetime] [timezone] summary [:: longdescription]\fR
.sp
\fIstartdatetime\fR and \fIenddatetime\fR must be either dates, times or datetimes in the format configured in the configuration file\&.
.sp
\fIstartdatetime\fR is a date: an all day event will be created, if \fIenddatetime\fR is not given, the event will last for one day\&.
.sp
\fIstartdatetime\fR is a datetime: the event will start at \fIstartdatetime\fR and end at \fIenddatetime\fR\&. If no \fIenddatetime\fR is given, the event will last one hour\&. If \fIenddatetime\fR is a time, the event will end at that time on the day it starts unless that would make it end before it starts in which case it will end at that time at the next day\&.
.sp
\fIstartdatetime\fR is a time: the event will start today at time and end at \fIenddatetime\fR\&. If \fIenddatetime\fR is a time it will also end today at that time, unless that would make it end before it starts in which case it will end at that time tomorrow\&.
.sp
The newly created event will be in \fItimezone\fR if given (must be in the Olson DB format, e\&.g\&. \fIEurope/Berlin\fR), if \fItimezone\fR is not given, the \fIlocal timezone\fR as configured in the configuration file will be used\&. It is currently not possible to create events that start and end in different timezones\&.
.sp
The leftover arguments (up to \fI::\fR) will be used as the summary of the event\&. Everything after \fI::\fR will be treated used as the event\(cqs description\&.
.sp
If no calendar is specified via \fI\-a CALENDAR\fR the event will be added to the default calendar\&.
.SS "printcalendars"
.sp
Print a list of all configured calendars\&.
.SH "FILES"
.sp
A sample config with commented examples is copied to \fI/etc/skel/khal\&.conf\fR\&. Copy the sample to one of two locations: \fI$HOME/\&.config/khal/khal\&.conf\fR or \fI$HOME/\&.khal/khal\&.conf\fR and edit to your liking\&.
.SH "AUTHOR"
.sp
\fBkhal\fR was mostly written by Christian Geier, with a lot of help by others, see \fICONTRIBUTORS\&.txt\fR in the \fIkhal\fR distribution\&.
.SH "RESOURCES"
.sp
Main web site: http://lostpackets\&.de/khal/ Please report bugs via the contact information at the above web site or via github: http://github\&.com/geier/khal/\&.
.SH "SEE ALSO"
.sp
vdirsyncer(1)
.SH "COPYING"
.sp
Copyright (C) 2013\-2014 Christian Geier and Contributors khal is released under the terms of the Expat/MIT license, see the \fICOPYING\fR file distributed with khal\&.
