# .readthedocs.yml

version: 2
sphinx:
    configuration: doc/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# This is the default, you can omit this
formats: []
