# .readthedocs.yml

version: 2
sphinx:
    configuration: doc/source/conf.py

python:
  version: 3.8
  install:
    - requirements: doc/requirements.txt
    - method: setuptools
      path: .

# This is the default, you can omit this
formats: []
